name: duolingo-to-markdown

on:
  schedule:
    - cron: '1 1 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: python packages installation
        run: |
          python -m pip install --upgrade pip
          pip install -r requests beautifulsoup

      - name: duolingo to markdown with fstrings
        env:
          DUOLINGO_USERNAME: ${{ secrets.DUOLINGO_USERNAME }}
          DUOLINGO_LANGUAGE_LENGTH: 3 # Optional. Defaults to 2. Language you want to show (are sort of higher experience to lower).
        run: python .github/scripts/duolingo-to-markdown.py

      - name: commit changes
        continue-on-error: true
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Updated duolingo-to-markdown daily progress" -a

      - name: push changes
        continue-on-error: true
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}\
          branch: main
